components:
  schemas:
    HealthSchema:
      description: Schema for the response containing health information.
      type: object
      xml:
        name: HealthSchema
      properties:
        success:
          type: boolean
          example: true
          default: false
        data:
          type: string
          example: OK
          default: ""