version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile/Backend.Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./src:/docker/backend
      - ./swagger/output:/docker/backend/swagger
    environment:
      - ORIGIN=localhost:4000
    tty: true
  swagger:
    build:
      context: .
      dockerfile: ./Dockerfile/Swagger.Dockerfile
    profiles: [ "dev" ]
    ports:
      - 30001:3001
    volumes:
      - ./swagger:/docker/swagger
      - ./../lib/models/swagger:/docker/swagger/flutter
    tty: true
