components:
  schemas:
    TaskSchema:
      description: Schema for representing a Task entity.
      type: object
      xml:
        name: TaskSchema
      properties:
        id:
          type: string
          format: uuid
          nullable: true
        name:
          type: string
          default: ""
        status:
          type: integer
          default: 0
        createdAt:
          type: string
          example: "2023/12/13 8:39:04"
          default: ""
        updatedAt:
          type: string
          example: "2023/12/13 8:39:04"
          default: ""
    ResponseTaskSchema:
      description: Schema for the response containing task information.
      type: object
      xml:
        name: ResponseTaskSchema
      properties:
        success:
          type: boolean
          example: true
          default: false
        data:
          type: array
          items:
            $ref: '#/components/schemas/TaskSchema'
          default: []
    RequestTaskPutSchema:
      description: Schema for the request containing name and status.
      type: object
      xml:
        name: RequestTaskPutSchema
      properties:
        name:
          type: string
          default: ""
        status:
          type: integer
          default: 0
    RequestTaskPostSchema:
      description: Schema for the request containing name.
      type: object
      xml:
        name: RequestTaskPostSchema
      properties:
        name:
          type: string
          default: ""