/**
 * todo API
 * This is todo API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Schema for representing a error entity.
 */
export interface ErrorSchema { 
    code: number;
    message: string;
    path?: string;
    timestamp?: string;
}