/**
 * todo API
 * This is todo API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskSchema } from './taskSchema';

/**
 * Schema for the response containing task information.
 */
export interface ResponseTaskSchema { 
    success?: boolean;
    data?: Array<TaskSchema>;
}