/**
 * todo API
 * This is todo API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Database model for representing a Task.
 */
export interface TaskModelSchemas { 
    id?: string;
    name?: string;
    status?: number;
    createdAt?: Date;
    updatedAt?: Date;
}