/**
 * todo API
 * This is todo API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Schema for representing a Task entity.
 */
export interface TaskSchema { 
    id?: string;
    name?: string;
    status?: number;
    createdAt?: string;
    updatedAt?: string;
}